# This is a basic workflow that is manually triggered

name: Cypress automation test - [basic]

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      wazuh-version:
        description: 'Wazuh Version'
        default: 'v4.3.4'
        required: true
      elastic-version: 
        description: 'Elastic Version'
        default: '7.16.3'
        required: true
      ubuntu-cypress-version: 
        description: 'Ubuntu Cypress Version'
        default: '3.0.0'
        required: true
      url-package:
        description: 'Package Download Url'
        required: false 
        default: 'https://packages-dev.wazuh.com/pre-release/ui/kibana/wazuh_kibana-4.3.4_7.16.3-1.zip'       

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-wazuh-kibana-app:
    name: Run setup environment wazuh kibana app
    runs-on: ubuntu-18.04
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'daily-app-team'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n esto es una prueba \n - resultado de la prueba"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.ACTIONS_SLACK_TOKEN }}