# This is a basic workflow that is manually triggered

name: Cypress automation test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      wazuh-manager-image: 
        description: 'Wazuh Manager Image'
        default: 'wazuh_manager_filebeat_sources_cmake'
        required: true
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-wazuh-kibana-app:
    name: Run setup environment wazuh kibana app
    runs-on: ubuntu-18.04
    steps:
     - name: Step 01 
       run: |
        echo " 
        Found '/home/automation/wazuh-cypress/.nvmrc' with version <17.3.0>
        Now using node v17.3.0 (npm v8.3.0)

        > wazuh-kibana-app-automation@1.0.0 cypress:run-headless:github-actions:xpack
        > cypress run --headless --browser chrome --config baseUrl=https://kibana:5601/ --env type=xpack
        1 of 2 failed (50%)                      11:35       11        8        3        -        - 
        
        " >> cypress.log
        
        tail --help
        echo "TEST_SKIPPED=$(tail cypress.log | grep -m 1 '.' | awk ' { print $(NF)}')" >> $GITHUB_ENV
        echo "TEST_PENDING=$(tail cypress.log | grep -m 1 '.' | awk ' { print $(NF-1)}')" >> $GITHUB_ENV
        echo "TEST_FAILING=$(tail cypress.log | grep -m 1 '.' | awk ' { print $(NF-2)}')" >> $GITHUB_ENV
        echo "TEST_PASSING=$(tail cypress.log | grep -m 1 '.' | awk ' { print $(NF-3)}')" >> $GITHUB_ENV
        echo "TEST_TOTAL=$(tail cypress.log | grep -m 1 '.' | awk ' { print $(NF-4)}')" >> $GITHUB_ENV
        echo "TEST_TIME=$(tail cypress.log | grep -m 1 '.' | awk ' { print $(NF-5)}')" >> $GITHUB_ENV
     - name: Step 02
       run: |
        echo "The following workflow was executed: ${{ github.workflow }}
        Test summary:
        -- Total Test: ${{ env.TEST_TOTAL }}
        -- Passing: ${{ env.TEST_PASSING }}
        -- Failing: ${{ env.TEST_FAILING }}
        -- Pending: ${{ env.TEST_PENDING }}
        -- Skipped: ${{ env.TEST_SKIPPED }}
        -- Total Time: ${{ env.TEST_TIME }}
        For more information visit: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    