# This is a basic workflow that is manually triggered

name: Cypress automation test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      wazuh-manager-image: 
        description: 'Wazuh Manager Image'
        default: 'wazuh_manager_filebeat_sources_cmake'
        required: true
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-wazuh-kibana-app:
    name: Run setup environment wazuh kibana app
    runs-on: ubuntu-18.04
    steps:
     - name: Step 01 
       run: |
        echo " 1 of 2 failed (50%)                      11:35       11        8        3        -        - " >> cypress.log
        tail --help
        echo "TEST_SKIPPED=$(tail -r cypress.log | grep -m 1 '.' | awk ' { print $(NF)}')" >> $GITHUB_ENV
        echo "TEST_PENDING=$(tail -r cypress.log | grep -m 1 '.' | awk ' { print $(NF-1)}')" >> $GITHUB_ENV
        echo "TEST_FAILING=$(tail -r cypress.log | grep -m 1 '.' | awk ' { print $(NF-2)}')" >> $GITHUB_ENV
        echo "TEST_PASSING=$(tail -r cypress.log | grep -m 1 '.' | awk ' { print $(NF-3)}')" >> $GITHUB_ENV
        echo "TEST_TOTAL=$(tail -r cypress.log | grep -m 1 '.' | awk ' { print $(NF-4)}')" >> $GITHUB_ENV
        echo "TEST_TIME=$(tail -r cypress.log | grep -m 1 '.' | awk ' { print $(NF-5)}')" >> $GITHUB_ENV
     - name: Step 02
       run: |
        echo "The following workflow was executed: ${{ github.workflow }}\n Test summary:\n-- Total Test: ${{ env.TEST_TOTAL }}\n-- Passing: ${{ env.TEST_PASSING }}\n-- Failing: ${{ env.TEST_FAILING }}\n-- Pending: ${{ env.TEST_PENDING }}\n-- Skipped: ${{ env.TEST_SKIPPED }}\n-- Total Time: ${{ env.TEST_TIME }}\n\nFor more information visit: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    